attributes:
  metadata:
    group: 'other'
  net1:
    type: "text"
    weight: 10
    value: ""
    label: "Net1 Network name"
  net2:
    type: "text"
    weight: 11
    value: ""
    label: "Net2 Network name"
  dns_key:
    type: "file"
    weight: 12
    value: ""
    label: "Key for DNS server"

